name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: [8.0.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-restore

      - name: Publish console app
        run: |
          dotnet publish -c Release -r win10-x64 --self-contained true --output ./publish
        continue-on-error: true

      - name: Upload published files
        uses: actions/upload-artifact@v2
        with:
          name: console-app
          path: ./publish
